config:
  submissions_input: "2023_submissions_to_assign.csv"
  reviewers_input: "2023_reviewers_to_assign.csv"
  min_reviews_per_person: 5
  max_reviews_per_person: 9
  min_reviewers_per_submission: 4
  max_reviewers_per_submission: 4
  assign_tutorials_to_anyone: true
  tutorial_coeff: 0.8
  debug_mode: true
