name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: Set up pixi
          uses: prefix-dev/setup-pixi@v0.5.1
          with:
            cache: true
            cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

        - name: List installed Python packages
          run: pixi list

        - name: Lint with ruff
          run: |
            pixi run ruff

        - name: Check formatting with black
          run: |
            pixi run black
