name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.x"

        - name: Install dependencies
          run: |
            python -m pip install uv
            python -m uv pip install --system --upgrade pip wheel
            python -m uv pip install --system ruff black

        - name: List installed Python packages
          run: python -m pip list

        - name: Lint with ruff
          run: ruff check .

        - name: Check formatting with black
          run: black . --check --verbose
